server:
  port: 8080
  servlet:
    session:
      timeout: 60
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 102400Mb
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    default-property-inclusion: non_null
    #字符串时间，用这行表示
    date-format: yyyy-MM-dd HH:mm:ss
    #设置为东八区时间
    timezone: GMT+8
    serialization:
      #想要值为2019-01-01
      write-dates-as-timestamps: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
      resources:
        static-locations: classpath:/static/
      devtools:
        restart:
          enabled: true
          exclude: static/**,templates/**,assets/**
  resources:
    static-locations: classpath:/static/
  devtools:
    restart:
      enabled: true
      exclude: static/**,templates/**,assets/**
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug