spring:
  profiles:
    active: dev

  #spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://47.105.144.39:3306/shoppe
##    username: root
##    password: 123456
#    url: jdbc:mysql://118.190.155.64:3306/shoppe
#    username: root
#    password: Es@2019
#    druid:
#      initial-size: 5
#      min-idle: 1
#      max-active: 50
#      max-wait: 3600
#      max-wait-thread-count: 15

#  rabbitmq:
#    host: 123.56.92.145
#    port: 15672
#    username: admin
#    password: admin
#    publisher-confirms: true
#    publisher-returns: true
#    connection-timeout: 20000
#  redis:
#    port: 6379
#    password:
#    host: 123.56.92.145
#    jedis:
#      pool:
#        max-idle: 8
#        max-active: 8
#        min-idle: 2
#    timeout: 2000
#  data:
#    mongodb:
#      uri: mongodb://123.56.92.145:27017/sun

